#!/bin/bash

#Kill Xcode
killall "Xcode"

#Generate Core Module
cd Core
xcodegen generate

#Generate Feature Module
cd ..
cd Account
xcodegen generate

#Generate App
cd ..
xcodegen generate

#Cocoapods Install
pod install

#Workspace grouping
cp -R "contents.xcworkspacedata" "FachriApp.xcworkspace/contents.xcworkspacedata" 


xcodeproj="xcodeproj"
command -v xcodeproj >/dev/null
if [ $? -eq 1 ]; then
echo >&2 "xcodeproj not found, please install xcodeproj. sudo gem install xcodeproj"
xcodeproj="&>";
exit 0
fi

#Change mach-o to fake static
./feature-module-static.rb

#Open Project
xed .