name: FachriApp
options:
  bundleIdPrefix: com.fachrifaul
  deploymentTarget: 
    iOS: 10.0
settings:
  DEVELOPMENT_TEAM: AK67DH72N8
targets:
  FachriApp:
    type: application
    platform: iOS
    sources:
      - FachriApp
    scheme:
      testTargets:
        - FachriAppTests
    dependencies:
      - sdk: Account.framework
        implicit: true
      - framework: Core.framework
        implicit: true
      - sdk: CoreText.framework
    settings:
      base:
        INFOPLIST_FILE: FachriApp/Info.plist
  FachriAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - FachriAppTests
    dependencies:
      - target: FachriApp
