name: FachriApp
options:
  bundleIdPrefix: com.fachrifaul
  deploymentTarget: 
    iOS: 10.0
settings:
  DEVELOPMENT_TEAM: AK67DH72N8
targets:
  FachriApp:
    type: application
    platform: iOS
    sources:
      - FachriApp
      # - path: Account/AccountResources
      # - target: AccountResources
      # - path: Account/AccountResources
      #   buildPhase:
      #     copyFiles:
      #       destination: plugins
      #       subpath: include/$(PRODUCT_NAME)
    scheme:
      testTargets:
        - FachriAppTests
    dependencies:
      - sdk: Account.framework
        implicit: true
      # - target: AccountResources
      - framework: Core.framework
        implicit: true
      - sdk: CoreText.framework
    settings:
      base:
        INFOPLIST_FILE: FachriApp/Info.plist
  FachriAppTests:
    type: bundle.unit-test
    platform: iOS
    sources: 
      - FachriAppTests
    dependencies:
      - target: FachriApp
  # Account:
  #   platform: iOS
  #   type: framework
  #   sources:
  #     - Account/Account/
  #   dependencies:
  #     - target: AccountResources
  #     - sdk: CoreText.framework
  # AccountTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources: 
  #     - Account/AccountTests/
  #   dependencies:
  #     - target: Account
  # AccountResources:
  #   type: bundle
  #   platform: iOS
  #   sources: 
  #     - Account/AccountResources/
  #     - path: Account/AccountResources/
  # Core:
  #   platform: iOS
  #   type: framework
  #   sources:
  #     - Core/Core/
  #   dependencies:
  #     - sdk: CoreText.framework
  # CoreTests:
  #   type: bundle.unit-test
  #   platform: iOS
  #   sources: 
  #     - Core/CoreTests/
  #   dependencies:
  #     - target: Core
